-- SQL CONSOLIDÉ : LOT #1 & LOT #2 (TITRE 4 - NS 01-001)
-- À exécuter dans le SQL Editor de proquelec pour charger le Corpus Doctrinal

WITH book AS (SELECT id FROM normative_books WHERE ref_code = 'NS 01.001')
INSERT INTO normative_articles (book_id, chapter_ref, article_ref, content_exact, safety_objective, application_conditions, prohibitions) VALUES 

-- LOT #1 : FONDATIONS & GÉNÉRALITÉS
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 410.1', 'La présente partie traite de la protection contre les chocs électriques dans les installations électriques. Elle se fonde sur la norme NF C 20-030, norme fondamentale de sécurité applicable à la protection des personnes et des animaux domestiques, destinée à donner les principes et prescriptions essentiels communs aux installations et aux matériels ou nécessaires à leur coordination. La règle essentielle pour la protection contre les chocs électriques, telle que définie dans la norme NF C 20-030, est que les parties actives dangereuses ne soient pas accessibles et que les parties conductrices accessibles ne soient pas dangereuses, tant dans des conditions normales que dans des conditions de défaut simple.', 'Garantir l''inaccessibilité des parties actives et la non-dangerosité des parties conductrices accessibles.', 'Installations électriques basse tension.', '{"les parties actives dangereuses ne soient pas accessibles"}'),
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 410.3.1', 'Une ou plusieurs des mesures de protection suivantes, constituées chacune d’une disposition de protection contre les contacts directs et d’une disposition de protection contre les contacts indirects, doivent être appliquées [...] : - mesure de protection par coupure automatique de l’alimentation, - mesure de protection par isolation double ou renforcée, - mesure de protection par séparation électrique pour l’alimentation d’un seul matériel, - mesure de protection par très basse tension.', 'Définir les mesures fondamentales de protection à appliquer systématiquement.', 'Toute installation ou partie d''installation.', NULL),
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 411.3.1.1', 'Dans chaque bâtiment, le conducteur principal de protection, la borne principale de terre et les éléments conducteurs suivants doivent être connectés à la liaison équipotentielle principale : - canalisations métalliques, par exemple eau, gaz, canalisations de chauffage central et de conditionnement d''air ; - éléments métalliques de la construction et armatures du béton armé ; - gaines ou tresses métalliques des câbles de communication. Lorsque de tels éléments conducteurs proviennent de l''extérieur du bâtiment, ils doivent être reliés à la liaison équipotentielle principale aussi près que possible de leur point d''entrée dans le bâtiment.', 'Assurer l''équipotentialité pour éviter les différences de potentiel dangereuses.', 'Dans chaque bâtiment (Liaison Équipotentielle Principale).', NULL),

-- LOT #2 : SLT, SURINTENSITÉS & SECTIONNEMENT
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 411.3.1.2', 'Les masses doivent être reliées à un conducteur de protection selon les conditions particulières des divers schémas des liaisons à la terre comme spécifié de 411.4 à 411.6. Les masses simultanément accessibles doivent être connectées à la même prise de terre.', 'Prévention des tensions de contact entre masses simultanément accessibles.', 'Tous schémas (TT, TN, IT).', NULL),
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 411.4.1', 'Les masses de l''installation doivent être reliées par des conducteurs de protection à la borne principale de terre de l’installation, laquelle doit être connectée au point de l’alimentation mis à la terre.', 'Raccordement des masses à la terre via le point de l''alimentation.', 'Schéma TN uniquement.', NULL),
((SELECT id FROM book), 'Titre 4 / Partie 4-41', 'Art 411.5.1', 'Toutes les masses protégées par un même dispositif de protection doivent être connectées à des conducteurs de protection reliés à une même prise de terre. Si plusieurs dispositifs de protection sont montés en série, cette prescription s''applique séparément à toutes les masses protégées par le même dispositif.', 'Raccordement des masses à des prises de terre distinctes.', 'Schéma TT uniquement.', NULL),
((SELECT id FROM book), 'Titre 4 / Partie 4-43', 'Art 430.1', 'Les conducteurs actifs doivent être protégés par un ou plusieurs dispositifs de coupure automatique contre les surcharges (433) et contre les courts-circuits (434). En outre, la protection contre les surcharges et la protection contre les courts-circuits doivent être coordonnées conformément à 435.', 'Éviter la détérioration des isolants et les incendies d''origine électrique.', 'Tous les conducteurs actifs.', NULL),
((SELECT id FROM book), 'Titre 4 / Partie 4-46', 'Art 461.2', 'Il doit être placé à l''origine de toute installation un dispositif de commande et un dispositif de sectionnement coupant tous les conducteurs actifs de l''ensemble de l''installation.', 'Pouvoir isoler physiquement l''intégralité de l''installation pour maintenance ou urgence.', 'À l''origine de toute installation.', NULL)

ON CONFLICT DO NOTHING;
